dist: bionic
language: python
python:
  - "3.9"


os:
- linux


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3
    - python3-pip


env:
  global:
    secure: C9bPH4vmEM8aSAywuOpvJVsu021v9pibQLCbN6cnUqgNJH5rLAsBRlFrh0WEIDVX0qz7pnvV8EWSFSEPOLEkfEC3IvK0+kxvlrzJuUNHsZcGExZSr4XqWKUghM4PWuSVCrZEfplgnbq3TqQm0gODfZdVUAFILU9KugYiCabGxXLvUVmvhYOx2bUAUbGg+Vq89jifbJXr5rqAsH/L9o5Uh2d/Y6KlWuPnQJn2Rjan7tNZsaSWcwJki30X7tVks2WD5iIryeUschpuNnuqGVB01R7CjK6fLDYalFGm8xGug0o4YMc4H9iypdzQa4E2zeCtZkptnZgzRrN7xK7HsQRP/Hm6AvAuovGyO4z3ZRSGpvGKyHbPCC33IS4YNvYEF/kusl+Y7cVFy0NT9gwp18AUDfMmTj7/O1hL80tLNHwJYbEb8by5PCu+16nwMCn8FzqoWn2wobAfoVbbO6QfIUZJw16hnQP2TStguYRHtnwJWbRfNiy23NQxHOxUB3SnpBcCmht7bAy0RIZORRgKGS1w2aoYlXX1jsl5UR9Tl0POjyIvIwkGQZOeDwmtO8XTWUV+pF//azW8TXqcj7B2TG1GlIyw+53NqWXKdKrCeU4uCcjlXpx5A9szG+Ty3P4Xbwm6fwhdxeum7lLwO6FGPje4j7Irc6n9ANlRSlUMRnCTo+I=


stages:
- test


jobs:
  include:
  - stage: test
    env: TITLE="Test and build documentation."
    script: "./ci/travis-ci.sh"

