name: release httpctrl

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Run multi-line script
      shell: bash
      run: ci/github-ci-release.sh
      with:
        HTTPCTRL_USERNAME: ${{ secrets.HTTPCTRL_USERNAME }}
        HTTPCTRL_PASSWORD: ${{ secrets.HTTPCTRL_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
