name: release httpctrl

on:
    workflow_call:
        inputs:
            requested_version:
                description: 'Specific version that is going to be used.'
                default: ''
                required: false
                type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Run multi-line script
      env:
        REQUESTED_VERSION: ${{ inputs.requested_version }}
        HTTPCTRL_USERNAME: ${{ secrets.HTTPCTRL_USERNAME }}
        HTTPCTRL_PASSWORD: ${{ secrets.HTTPCTRL_PASSWORD }}
        HTTPCTRL_EMAIL: ${{ secrets.HTTPCTRL_EMAIL }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      shell: bash
      run: ci/github-ci-release.sh

